---

- name: "Debian | Packages | Install required packages"
  package:
    name: "{{ aws_config_cli_packages }}"
  tags: 'aws_config_cli_requirements'

- name: 'Install AWS CLI'
  pip:
    name: awscli
    executable: pip3
  tags: 'aws_config_cli_requirements'
