---

- name: "RHEL | Packages | Install required packages"
  yum:
    name: "{{ aws_config_cli_packages }}"
    state: "{{ aws_config_cli_packages_state }}"
    update_cache: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  tags: 'aws_config_cli_requirements'

- name: 'RHEL | Install AWS CLI'
  pip:
    name: awscli
    state: latest
    executable: pip3
  tags: 'aws_config_cli_requirements'
  vars:
    ansible_python_interpreter: /usr/bin/python3
