---
- name: Converge
  hosts: all

  vars:
    aws_config_cli_user: 'user'
    aws_config_cli_group: 'user'

    # common
    aws_config_cli_config:
      default:
        output: 'json'
        region: 'ap-southeast-2'

    aws_config_cli_credentials:
      default:
        aws_access_key_id: 'YOUR_ACCESS_KEY_ID'
        aws_secret_access_key: 'YOUR_SECRET_ACCESS_KEY'

  tasks:
    - name: "Include aws-config-cli"
      include_role:
        name: "aws-config-cli"
