---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -c yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO}"
    pre_build_image: true
    privileged: true
    groups:
      - "${MOLECULE_DISTRO_GROUPS}"
provisioner:
  name: ansible
  log: true
  lint: |
    ansible-lint
  playbooks:
    prepare: prepare_${MOLECULE_DISTRO_GROUPS}.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
  lint: |
    flake8
