---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -c yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: EL7
    image: centos:7
    pre_build_image: true
    groups:
      - rhel_family
  - name: Xenial
    image: ubuntu:16.04
    pre_build_image: true
    groups:
      - debian_family
  - name: Bionic
    image: ubuntu:18.04
    pre_build_image: true
    groups:
      - debian_family
  - name: Focal
    image: ubuntu:20.04
    pre_build_image: true
    groups:
      - debian_family
provisioner:
  name: ansible
  log: true
  lint: |
    ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
  lint: |
    flake8
