---

- name: "Prepare Ubuntu / Debian"
  hosts: debian_family
  gather_facts: false
  tasks:
    - name: "Install python for Ansible"
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python3-minimal python3-apt)
      changed_when: false

- name: "Prepare RHEL"
  hosts: rhel_family
  gather_facts: false
  tasks:
    - name: "Install python for Ansible"
      raw: test -e /usr/bin/python || (yum install -y python3 python-simplejson)
      changed_when: false

- name: "Get info"
  hosts: all
  gather_facts: true

  tasks:
    - name: "OS"
      debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}"
